[package]
name = "es9"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
cpal = "0.15.3"
rustyline = "14.0.0"
tokio = { version = "1.37.0", features = ["full", "net"] }
